# Generated by Django 2.2.7 on 2019-12-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('profile_photo_path', models.CharField(max_length=1000)),
                ('birthdate', models.DateField(blank=True)),
            ],
        ),
    ]
